name: CMake

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download SEAL
      run: curl https://github.com/microsoft/SEAL/archive/refs/tags/v3.6.5.tar.gz -O v3.6.5.tar.gz
        
    - name: Extract SEAL
      run: 
        gzip -d < v3.6.5.tar.gz | tar xf -
        cd SEAL-3.6.5

    - name: Configure CMake
      run: cmake ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
